id: AC0DEF319
title: f01F6
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.720851
  last_modified_at: 2022-05-27 18:41:15.720854
