id: AC0DEF319
title: fAB86
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.951006
  last_modified_at: 2022-05-27 18:41:15.951009
