id: AC0DEF319
title: fD81A
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:16.014976
  last_modified_at: 2022-05-27 18:41:16.014979
