id: AC0DEF319
title: fEA19
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:16.042719
  last_modified_at: 2022-05-27 18:41:16.042721
