id: AC0DEF319
title: f5053
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.835162
  last_modified_at: 2022-05-27 18:41:15.835165
