id: AC0DEF319
title: f9000
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.905946
  last_modified_at: 2022-05-27 18:41:15.905948
