id: AC0DEF319
title: fA2C0
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.936438
  last_modified_at: 2022-05-27 18:41:15.936441
