id: AC0DEF319
title: fF5E5
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:16.059227
  last_modified_at: 2022-05-27 18:41:16.059230
