id: AC0DEF319
title: fA93B
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.949135
  last_modified_at: 2022-05-27 18:41:15.949138
