id: AC0DEF319
title: fA66A
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.942091
  last_modified_at: 2022-05-27 18:41:15.942093
