id: AC0DEF319
title: fF79F
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:16.063323
  last_modified_at: 2022-05-27 18:41:16.063325
