id: AC0DEF319
title: fF2B6
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:16.058271
  last_modified_at: 2022-05-27 18:41:16.058274
