id: AC0DEF319
title: f2AB5
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.780702
  last_modified_at: 2022-05-27 18:41:15.780705
