id: AC0DEF319
title: f64FC
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.851245
  last_modified_at: 2022-05-27 18:41:15.851248
