id: AC0DEF319
title: f1186
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.743107
  last_modified_at: 2022-05-27 18:41:15.743110
