id: AC0DEF319
title: f814D
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.890562
  last_modified_at: 2022-05-27 18:41:15.890564
