id: AC0DEF319
title: fD0A0
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:16.004314
  last_modified_at: 2022-05-27 18:41:16.004317
