id: AC0DEF319
title: f75D2
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 18:41:15.872921
  last_modified_at: 2022-05-27 18:41:15.872924
